[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"

[env]
CXX = "aarch64-unknown-linux-gnu-g++"
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_SYSROOT_DIR = "/Users/aliimran/Repos/antidote/cross-sysroot"
PKG_CONFIG_PATH = "/Users/aliimran/Repos/antidote/cross-sysroot/usr/lib/aarch64-linux-gnu/pkgconfig"
